### ISSUE TITLE
Can't reproduce .Rmd code because non existing function

### ISSUE THREAD

**Issue by thomasdebeus** [callumgwtaylor/snakes#2]
Hi Callum,

First off, thanks for your thorough and detailed Blog post on webscraping with RSelenium, it's awesome! 

I'm a journalist from Amsterdam and I already use R for analysis and visualisation. For my job at the newspaper I once in a while have to deal with javascript generated webpages. I want to learn RSelenium for scraping, built original datasets and find stories in them.

Now I loaded your [snake_countries_workthrough_selenium.Rmd](https://github.com/callumgwtaylor/snakes/edit/master/data-raw/snake_countries_workthrough_selenium.Rmd) file and try to reproduce and understand each function. Though I get stuck at the `if(more_pages == TRUE){` statement. When I try to run it, the console gives an error that it can't find `object 'download_secondary_country'` in the `purrr::pmap()` function on **line 168**. Now that seems logical because that function is not created in this file and it's nowhere to be found in other files on you github repository.

Thanks in advance!

**Comment by callumgwtaylor** [comment]
Hi Thomas,

That was a mistake on my part. I removed a lot of functions from the package when I decided that it should just be an easy way for people to load the data, rather than scrape it themselves.  But I've put them back into the workthrough now, plus fixed another couple of mistakes I'd just found, and it seems to be working ok for me!

Let me know if the new workthrough runs properly for you, or if you're still having issues.

Thanks,

Callum
