### ISSUE TITLE
"docker run -d -p 4445:4444 selenium/standalone-chrome" doesnt work

### ISSUE THREAD

**Issue by Rennepink** [callumgwtaylor/snakes#5]
Hi there,

I am trying to connect to chemcalc using this package. However, I get this error:
$ docker run -d -p 4445:4444 selenium/standalone-chrome
C:\Program Files\Docker Toolbox\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Can anyone tell me what I am doing wrong?
Thanks

**Comment by callumgwtaylor** [comment]
Hi Rennepink!

When you say you're trying to use this package to connect, what do you mean? This package just has the data from the WHO snake database, rather than the way to connect to other methods.

https://callumgwtaylor.github.io/blog/2018/02/01/using-rselenium-and-docker-to-webscrape-in-r-using-the-who-snake-database/

In this blog post above I shared the code I used to connect to the website, but you do need to install RSelenium and Docker seperately before attempting it. Have you done that?
